version: 0.2

env:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

phases:
  install:
    runtime-versions:
      java: corretto25
    commands:
      - echo "Java Version"
      - java -version
      - chmod +x gradlew

  pre_build:
    commands:
      - ./gradlew --version

  build:
    commands:
      - echo "Building project..."
      - ./gradlew clean classes

  post_build:
    commands:
      - echo "Compiled classes:"
      - find build/classes/java/main -type f

artifacts:
  base-directory: build/classes/java/main
  files:
    - '**/*'

cache:
  paths:
    - /root/.gradle/caches/**/*
    - /root/.gradle/wrapper/**/*
